import sys

import numpy as np


def proc(i, x, y):
    """
    Helper function to get the value of a given element if the ndarray was transposed.
    Args:
        i: int, the element
        x: int, the x axis size.
        y: int, the y axis size.
    Returns:
        int, the value of the element.
    """
    return np.where(i < 0, -1, (i % x) * y + (i // x))


"""
Helper script to convert a tmx csv file (generated by Tiled tilemap editor) to a numpy array and save it.
Sys args:
    input_file: str, the path to the input csv file.
    output_file: str, the path to the output npy file.
    starting_gid: int, the starting global id of the tileset.
    x: int, the x axis size.
    y: int, the y axis size.
"""

if len(sys.argv) != 6:
    print(
        "Usage: python tmx_csv_to_npy.py <input_file> <output_file> <starting_gid> <x> <y>"
    )
    sys.exit(1)
starting_gid = int(sys.argv[3])
x = int(sys.argv[4])
y = int(sys.argv[5])
a = np.loadtxt(sys.argv[1], delimiter=",", dtype=int)
np.save(sys.argv[2], proc(a - starting_gid, x, y))
